export default [
  {
    name: "TypeScript",
    description: "Strongly typed JavaScript superset",
    field: "Language-Compiled",
    pros: [
      "Static typing reduces runtime errors",
      "Excellent IDE support",
      "Gradual adoption possible",
    ],
    cons: ["Additional compilation step", "Learning curve for complex types"],
    icon: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg",
    openSource: true,
    active: true,
    custom: false,
    released: "2012-10-01",
    currentVersion: "5.3.3",
    stability: "Stable",
    github: {
      stars: 94800,
      forks: 12200,
      lastCommit: "2024-02-15",
      openIssues: 5800,
    },
    license: {
      type: "Apache-2.0",
      cost: "Free",
    },
    learningCurve: "Intermediate",
  },
  {
    name: "Kubernetes",
    description: "Container orchestration system",
    field: "Container-Orchestration",
    pros: [
      "Industry standard for container management",
      "Self-healing capabilities",
      "Highly scalable",
    ],
    cons: ["Complex setup and configuration", "Steep learning curve"],
    icon: "https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg",
    openSource: true,
    active: true,
    custom: false,
    released: "2014-06-07",
    currentVersion: "1.29",
    stability: "Stable",
    github: {
      stars: 105000,
      forks: 38500,
      lastCommit: "2024-02-18",
      openIssues: 3200,
    },
    license: {
      type: "Apache-2.0",
      cost: "Free",
    },
    learningCurve: "Advanced",
  },
  {
    name: "Figma",
    description: "Collaborative interface design tool",
    field: "Design-System",
    pros: [
      "Real-time collaboration",
      "Browser-based with offline mode",
      "Powerful prototyping",
    ],
    cons: [
      "Limited offline functionality",
      "Performance issues with large files",
    ],
    icon: "https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg",
    openSource: false,
    active: true,
    custom: false,
    released: "2016-09-27",
    currentVersion: "116.4",
    stability: "Stable",
    license: {
      type: "Proprietary",
      cost: "Freemium",
    },
    learningCurve: "Beginner",
  },
  {
    name: "Jest",
    description: "JavaScript testing framework",
    field: "Unit-Testing",
    pros: [
      "Zero-config for most projects",
      "Fast and reliable",
      "Great snapshot testing",
    ],
    cons: [
      "Can be slow for large codebases",
      "Mocking system can be confusing",
    ],
    icon: "https://jestjs.io/img/opengraph.png",
    openSource: true,
    active: true,
    custom: false,
    released: "2014-05-13",
    currentVersion: "29.7.0",
    stability: "Stable",
    github: {
      stars: 42700,
      forks: 6400,
      lastCommit: "2024-02-16",
      openIssues: 420,
    },
    license: {
      type: "MIT",
      cost: "Free",
    },
    learningCurve: "Intermediate",
  },
  {
    name: "MongoDB",
    description: "Document-oriented NoSQL database",
    field: "Database-Document",
    pros: [
      "Flexible schema design",
      "Horizontal scaling",
      "Powerful query language",
    ],
    cons: ["No native joins", "Memory usage can be high"],
    icon: "https://upload.wikimedia.org/wikipedia/commons/9/93/MongoDB_Logo.svg",
    openSource: true,
    active: true,
    custom: false,
    released: "2009-02-11",
    currentVersion: "7.0",
    stability: "Stable",
    github: {
      stars: 24700,
      forks: 5800,
      lastCommit: "2024-02-17",
      openIssues: 1200,
    },
    license: {
      type: "Apache-2.0",
      cost: "Free",
    },
    learningCurve: "Intermediate",
  },
  {
    name: "TensorFlow.js",
    description: "Machine learning in JavaScript",
    field: "Machine-Learning",
    pros: [
      "Run ML models in browser",
      "Pre-trained models available",
      "GPU acceleration support",
    ],
    cons: [
      "Limited compared to Python version",
      "Performance constraints in browser",
    ],
    icon: "https://upload.wikimedia.org/wikipedia/commons/3/31/TensorFlow_logo.svg",
    openSource: true,
    active: true,
    custom: false,
    released: "2018-03-30",
    currentVersion: "4.17.0",
    stability: "Stable",
    github: {
      stars: 18300,
      forks: 2900,
      lastCommit: "2024-02-14",
      openIssues: 350,
    },
    license: {
      type: "Apache-2.0",
      cost: "Free",
    },
    learningCurve: "Advanced",
  },
  {
    name: "Postman",
    description: "API development environment",
    field: "Developer-Tooling",
    pros: [
      "Excellent API testing features",
      "Team collaboration",
      "Mock server capability",
    ],
    cons: ["Resource intensive", "Learning curve for advanced features"],
    icon: "https://voyager.postman.com/logo/postman-logo-icon-orange.svg",
    openSource: false,
    active: true,
    custom: false,
    released: "2012-06-01",
    currentVersion: "10.22",
    stability: "Stable",
    license: {
      type: "Proprietary",
      cost: "Freemium",
    },
    learningCurve: "Beginner",
  },
  {
    name: "Solidity",
    description: "Contract-oriented programming language",
    field: "Blockchain-Web3",
    pros: [
      "Standard for Ethereum smart contracts",
      "Growing ecosystem",
      "Static typing",
    ],
    cons: ["Immature tooling", "Security pitfalls"],
    icon: "https://upload.wikimedia.org/wikipedia/commons/0/05/Solidity_logo.svg",
    openSource: true,
    active: true,
    custom: false,
    released: "2014-08-01",
    currentVersion: "0.8.25",
    stability: "Stable",
    github: {
      stars: 21400,
      forks: 5800,
      lastCommit: "2024-02-15",
      openIssues: 420,
    },
    license: {
      type: "GPL",
      cost: "Free",
    },
    learningCurve: "Advanced",
  },
  {
    name: "Three.js",
    description: "JavaScript 3D library",
    field: "AR-VR",
    pros: [
      "Makes WebGL accessible",
      "Large collection of examples",
      "Active community",
    ],
    cons: [
      "Performance optimization challenging",
      "Documentation could be better",
    ],
    icon: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Three.js_Icon.svg",
    openSource: true,
    active: true,
    custom: false,
    released: "2010-04-24",
    currentVersion: "r162",
    stability: "Stable",
    github: {
      stars: 95800,
      forks: 35200,
      lastCommit: "2024-02-18",
      openIssues: 1100,
    },
    license: {
      type: "MIT",
      cost: "Free",
    },
    learningCurve: "Intermediate",
  },
  {
    name: "Vercel",
    description: "Cloud platform for frontend developers",
    field: "Cloud-Provider",
    pros: [
      "Excellent Next.js integration",
      "Simple deployment workflow",
      "Global CDN",
    ],
    cons: ["Vendor lock-in concerns", "Limited backend capabilities"],
    icon: "https://assets.vercel.com/image/upload/q_auto/front/favicon/vercel/180x180.png",
    openSource: false,
    active: true,
    custom: false,
    released: "2015-10-01",
    currentVersion: null,
    stability: "Stable",
    license: {
      type: "Proprietary",
      cost: "Freemium",
    },
    learningCurve: "Beginner",
  },
];
